# Generated by Django 5.2.5 on 2025-08-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='URL de la photo de profil'),
        ),
    ]
