# Generated by Django 5.2.5 on 2025-08-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cree_le',
        ),
        migrations.RemoveField(
            model_name='user',
            name='derniere_connexion_le',
        ),
    ]
