# Generated by Django 5.2.5 on 2025-10-12 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_first_name_user_last_name'),
        ('projects', '0007_etape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('projet_retard', 'Projet en retard'), ('tache_retard', 'Tâche en retard'), ('session_connexion', 'Session de connexion'), ('message_chat', 'Message de chat'), ('systeme_maintenance', 'Maintenance système'), ('annonce_generale', 'Annonce générale'), ('tache_assignee', 'Tâche assignée'), ('tache_terminee', 'Tâche terminée'), ('projet_chef', 'Chef de projet'), ('projet_valide', 'Projet validé'), ('projet_en_cours', 'Projet en cours'), ('projet_retard_perso', 'Projet en retard (personnel)'), ('equipe_membre', "Membre d'équipe"), ('etape_terminee', 'Étape terminée'), ('document_valide', 'Document validé'), ('document_rejete', 'Document rejeté')], max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='bell', max_length=50)),
                ('couleur', models.CharField(default='blue', max_length=20)),
                ('est_generale', models.BooleanField(default=False, help_text='True pour notifications générales, False pour personnelles')),
            ],
            options={
                'verbose_name': 'Type de notification',
                'verbose_name_plural': 'Types de notifications',
                'db_table': 'notification_types',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('description_detaillee', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='normale', max_length=20)),
                ('statut', models.CharField(choices=[('non_lue', 'Non lue'), ('lue', 'Lue'), ('archivee', 'Archivée')], default='non_lue', max_length=20)),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('lue_le', models.DateTimeField(blank=True, null=True)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_creees', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(blank=True, help_text='Null pour notifications générales', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.etape')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.service')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.tache')),
                ('type_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode_envoi', models.CharField(choices=[('websocket', 'WebSocket'), ('email', 'Email'), ('push', 'Push'), ('sms', 'SMS')], max_length=50)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec'), ('en_attente', 'En attente')], max_length=20)),
                ('message_erreur', models.TextField(blank=True)),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Log de notification',
                'verbose_name_plural': 'Logs de notifications',
                'db_table': 'notification_logs',
                'ordering': ['-envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_push', models.BooleanField(default=True)),
                ('notifications_chat', models.BooleanField(default=True)),
                ('preferences_par_type', models.JSONField(blank=True, default=dict)),
                ('heure_debut', models.TimeField(default='08:00')),
                ('heure_fin', models.TimeField(default='18:00')),
                ('jours_semaine', models.JSONField(blank=True, default=list)),
                ('frequence_digest', models.CharField(choices=[('immediat', 'Immédiat'), ('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire')], default='immediat', max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('est_systeme', models.BooleanField(default=False, help_text='Message système (connexion/déconnexion)')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.service')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'db_table': 'chat_messages',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['cree_le'], name='chat_messag_cree_le_fdc51c_idx'), models.Index(fields=['expediteur', 'cree_le'], name='chat_messag_expedit_85cba3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'statut', 'cree_le'], name='notificatio_destina_1715f2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification', 'cree_le'], name='notificatio_type_no_8627d3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['projet', 'cree_le'], name='notificatio_projet__be0179_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tache', 'cree_le'], name='notificatio_tache_i_14f24e_idx'),
        ),
    ]
