# Generated by Django 5.2.5 on 2025-11-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_etape_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='code',
            field=models.CharField(choices=[('projet_retard', 'Projet en retard'), ('tache_retard', 'Tâche en retard'), ('projet_debut', 'Projet qui commence'), ('tache_debut', 'Tâche qui commence'), ('session_connexion', 'Session de connexion'), ('message_chat', 'Message de chat'), ('systeme_maintenance', 'Maintenance système'), ('annonce_generale', 'Annonce générale'), ('projet_valide', 'Projet validé'), ('projet_en_cours', 'Projet en cours'), ('document_valide', 'Document validé'), ('document_rejete', 'Document rejeté'), ('phase_terminee', 'Phase terminée'), ('permission_accordee', 'Permission accordée'), ('commentaire_document', 'Commentaire sur document'), ('historique_document', 'Historique document'), ('document_televerse', 'Document téléversé'), ('utilisateur_inscrit', 'Nouvel utilisateur'), ('service_cree', 'Nouveau service'), ('role_cree', 'Nouveau rôle'), ('projet_supprime', 'Projet supprimé'), ('tache_supprimee', 'Tâche supprimée'), ('document_supprime', 'Document supprimé'), ('tache_assignee', 'Tâche assignée'), ('tache_terminee', 'Tâche terminée'), ('projet_chef', 'Chef de projet'), ('projet_retard_perso', 'Projet en retard (personnel)'), ('equipe_membre', "Membre d'équipe"), ('permission_projet', 'Permission sur projet'), ('notification_personnelle', 'Notification personnelle')], max_length=50, unique=True),
        ),
    ]
