# Generated by Django 5.2.5 on 2025-08-25 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_first_name_user_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code du projet')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('nom_createur', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du créateur')),
                ('description', models.TextField(verbose_name='Description')),
                ('objectif', models.TextField(verbose_name='Objectif')),
                ('budget', models.CharField(blank=True, max_length=250, null=True, verbose_name='Budget')),
                ('type', models.CharField(max_length=250, verbose_name='Type de projet')),
                ('statut', models.CharField(choices=[('termine', 'Terminé'), ('en_attente', 'En attente'), ('hors_delai', 'Hors délai'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('haut', 'Haute'), ('moyen', 'Moyenne'), ('intermediaire', 'Intermédiaire'), ('bas', 'Basse')], default='haut', max_length=20, verbose_name='Priorité')),
                ('etat', models.CharField(choices=[('On', 'Actif'), ('Off', 'Inactif')], default='On', max_length=3, verbose_name='État')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('nom_update', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom de la dernière mise à jour')),
                ('debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('estimation_jours', models.IntegerField(blank=True, null=True, verbose_name='Estimation en jours')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_proprietaire', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire du projet')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'projets',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MembreProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_projet', models.CharField(max_length=80, verbose_name='Rôle dans le projet')),
                ('ajoute_le', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.service', verbose_name='Service')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_membre', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Membre de projet',
                'verbose_name_plural': 'Membres de projet',
                'db_table': 'membres_projet',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_etat', models.CharField(max_length=50, verbose_name='État précédent')),
                ('vers_etat', models.CharField(max_length=50, verbose_name='Nouvel état')),
                ('effectue_le', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('par_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant effectué le changement')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_etat', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': "Historique d'état",
                'verbose_name_plural': "Historiques d'état",
                'db_table': 'historiques_etat',
                'ordering': ['-effectue_le'],
            },
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['code'], name='projets_code_8a9b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['statut'], name='projets_statut_d31986_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['priorite'], name='projets_priorit_879696_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['proprietaire'], name='projets_proprie_3c8f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['type'], name='projets_type_d20d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='membreprojet',
            index=models.Index(fields=['projet'], name='membres_pro_projet__0ce36e_idx'),
        ),
        migrations.AddIndex(
            model_name='membreprojet',
            index=models.Index(fields=['utilisateur'], name='membres_pro_utilisa_877555_idx'),
        ),
        migrations.AddIndex(
            model_name='membreprojet',
            index=models.Index(fields=['service'], name='membres_pro_service_019224_idx'),
        ),
        migrations.AddIndex(
            model_name='membreprojet',
            index=models.Index(fields=['role_projet'], name='membres_pro_role_pr_a616cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membreprojet',
            unique_together={('projet', 'utilisateur')},
        ),
        migrations.AddIndex(
            model_name='historiqueetat',
            index=models.Index(fields=['projet', 'effectue_le'], name='historiques_projet__69deca_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueetat',
            index=models.Index(fields=['par_utilisateur'], name='historiques_par_uti_57b134_idx'),
        ),
    ]
