# Generated by Django 5.2.5 on 2025-08-25 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(verbose_name='Description')),
                ('permissions_par_defaut', models.JSONField(default=list, verbose_name='Permissions par défaut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Rôle de projet',
                'verbose_name_plural': 'Rôles de projet',
                'db_table': 'roles_projet',
            },
        ),
        migrations.CreateModel(
            name='PermissionProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('voir', 'Voir le projet'), ('modifier', 'Modifier le projet'), ('supprimer', 'Supprimer le projet'), ('valider', 'Valider le projet'), ('gerer_membres', 'Gérer les membres'), ('gerer_permissions', 'Gérer les permissions'), ('voir_historique', "Voir l'historique"), ('exporter', 'Exporter le projet')], max_length=20, verbose_name='Permission')),
                ('accordee_le', models.DateTimeField(auto_now_add=True, verbose_name="Date d'accord")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('accordee_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_accordees', to=settings.AUTH_USER_MODEL, verbose_name='Accordée par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_utilisateurs', to='projects.projet', verbose_name='Projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_projets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission de projet',
                'verbose_name_plural': 'Permissions de projet',
                'db_table': 'permissions_projet',
                'indexes': [models.Index(fields=['projet', 'utilisateur'], name='permissions_projet__786cd5_idx'), models.Index(fields=['permission'], name='permissions_permiss_dc4495_idx'), models.Index(fields=['active'], name='permissions_active_0ccd67_idx')],
                'unique_together': {('projet', 'utilisateur', 'permission')},
            },
        ),
    ]
