# Generated by Django 5.2.5 on 2025-08-27 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_roleprojet_permissionprojet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleProjet',
        ),
        migrations.AlterModelOptions(
            name='historiqueetat',
            options={'verbose_name': "Historique d'état", 'verbose_name_plural': "Historiques d'état"},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RemoveIndex(
            model_name='projet',
            name='projets_type_d20d0e_idx',
        ),
        migrations.AlterField(
            model_name='historiqueetat',
            name='de_etat',
            field=models.CharField(max_length=50, verbose_name='État de départ'),
        ),
        migrations.AlterField(
            model_name='historiqueetat',
            name='par_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_etat_crees', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur qui a effectué le changement'),
        ),
        migrations.AlterField(
            model_name='historiqueetat',
            name='vers_etat',
            field=models.CharField(max_length=50, verbose_name="État d'arrivée"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='nom_update',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nom de la personne qui a mis à jour'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['etat'], name='projets_etat_04024c_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['cree_le'], name='projets_cree_le_60deaf_idx'),
        ),
    ]
