# Generated by Django 5.2.5 on 2025-08-27 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_role_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la tâche')),
                ('statut', models.CharField(choices=[('termine', 'Terminé'), ('en_attente', 'En attente'), ('hors_delai', 'Hors délai'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('priorite', models.CharField(choices=[('haut', 'Haute'), ('moyen', 'Moyenne'), ('intermediaire', 'Intermédiaire'), ('bas', 'Basse')], default='haut', max_length=20, verbose_name='Priorité')),
                ('phase', models.CharField(choices=[('conception', 'Conception'), ('build', 'Build'), ('uat', 'UAT'), ('lancement', 'Lancement'), ('suivi', 'Suivi'), ('fin_de_vie', 'Fin de vie')], max_length=50, verbose_name='Phase')),
                ('debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('nbr_jour_estimation', models.IntegerField(blank=True, null=True, verbose_name="Nombre de jours d'estimation")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projects.projet', verbose_name='Projet')),
                ('tache_dependante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_dependantes', to='projects.tache', verbose_name='Tâche dépendante')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'db_table': 'taches',
                'indexes': [models.Index(fields=['projet', 'statut', 'phase'], name='idx_taches'), models.Index(fields=['projet'], name='taches_projet__3f9281_idx'), models.Index(fields=['statut'], name='taches_statut_6901dd_idx'), models.Index(fields=['phase'], name='taches_phase_46c294_idx'), models.Index(fields=['assigne_a'], name='taches_assigne_38befb_idx'), models.Index(fields=['tache_dependante'], name='taches_tache_d_935fd0_idx'), models.Index(fields=['debut'], name='taches_debut_10b359_idx'), models.Index(fields=['fin'], name='taches_fin_e2c6cb_idx')],
            },
        ),
    ]
