# Generated by Django 5.2.5 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tache'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description de la tâche'),
        ),
    ]
