# Generated by Django 5.2.5 on 2025-09-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tache_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la phase')),
                ('ordre', models.PositiveIntegerField(unique=True, verbose_name='Ordre de la phase')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la phase')),
                ('active', models.BooleanField(default=True, verbose_name='Phase active')),
            ],
            options={
                'verbose_name': 'Phase de projet',
                'verbose_name_plural': 'Phases de projet',
                'db_table': 'phases_projet',
                'ordering': ['ordre'],
                'indexes': [models.Index(fields=['ordre'], name='phases_proj_ordre_5fb3b1_idx'), models.Index(fields=['active'], name='phases_proj_active_30f6aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjetPhaseEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminee', models.BooleanField(default=False, verbose_name='Phase terminée')),
                ('ignoree', models.BooleanField(default=False, verbose_name='Phase ignorée')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire sur la phase')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_etat', to='projects.phaseprojet', verbose_name='Phase')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases_etat', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'État de phase de projet',
                'verbose_name_plural': 'États de phases de projet',
                'db_table': 'projets_phases_etat',
                'ordering': ['phase__ordre'],
                'indexes': [models.Index(fields=['projet', 'phase'], name='projets_pha_projet__3bbfa5_idx'), models.Index(fields=['terminee'], name='projets_pha_termine_89f6da_idx'), models.Index(fields=['ignoree'], name='projets_pha_ignoree_26c6f7_idx'), models.Index(fields=['date_debut'], name='projets_pha_date_de_21888c_idx'), models.Index(fields=['date_fin'], name='projets_pha_date_fi_4e394f_idx')],
                'unique_together': {('projet', 'phase')},
            },
        ),
    ]
