# Generated by Django 5.2.5 on 2025-09-15 10:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_phaseprojet_projetphaseetat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'étape")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Description de l'étape")),
                ('ordre', models.PositiveIntegerField(verbose_name='Ordre dans la phase')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name="Statut de l'étape")),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='normale', max_length=20, verbose_name='Priorité')),
                ('date_debut_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date de début prévue')),
                ('date_fin_prevue', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('progression_pourcentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progression (%)')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('notes_internes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('phase_etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='projects.projetphaseetat', verbose_name='Phase du projet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_responsable', to=settings.AUTH_USER_MODEL, verbose_name="Responsable de l'étape")),
            ],
            options={
                'verbose_name': 'Étape',
                'verbose_name_plural': 'Étapes',
                'db_table': 'etapes',
                'ordering': ['phase_etat__phase__ordre', 'ordre'],
                'indexes': [models.Index(fields=['phase_etat', 'ordre'], name='etapes_phase_e_45af8a_idx'), models.Index(fields=['statut'], name='etapes_statut_a619eb_idx'), models.Index(fields=['priorite'], name='etapes_priorit_06a00e_idx'), models.Index(fields=['responsable'], name='etapes_respons_fa88fb_idx'), models.Index(fields=['date_debut_prevue'], name='etapes_date_de_ef8337_idx'), models.Index(fields=['date_fin_prevue'], name='etapes_date_fi_8d03ce_idx')],
                'unique_together': {('phase_etat', 'ordre')},
            },
        ),
    ]
