# Generated by Django 5.2.5 on 2025-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_etape'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='projet',
            name='termine',
            field=models.BooleanField(default=False, verbose_name='Projet terminé'),
        ),
    ]
