# Generated by Django 5.2.5 on 2025-10-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_project_completion_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='termine',
        ),
    ]
