# Generated by Django 5.2.5 on 2025-11-09 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_completion_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tache',
            name='taches_assigne_38befb_idx',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='assigne_a',
        ),
        migrations.AddField(
            model_name='tache',
            name='assigne_a',
            field=models.ManyToManyField(blank=True, related_name='taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignés à'),
        ),
    ]
