# Generated by Django 5.2.5 on 2025-11-10 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_change_assigne_a_to_manytomany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projects.etape', verbose_name='Étape'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='phase',
            field=models.CharField(blank=True, choices=[('expression_besoin', 'Expression du besoin'), ('etudes_faisabilite', 'Études de faisabilité'), ('conception', 'Conception'), ('developpement', 'Développement / Implémentation'), ('lancement_commercial', 'Lancement commercial'), ('suppression_offre', "Suppression d'une offre")], max_length=50, null=True, verbose_name='Phase'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['etape'], name='taches_etape_i_a2cd10_idx'),
        ),
    ]
