# Generated by Django 5.2.5 on 2025-11-11 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def remove_etape_related_data(apps, schema_editor):
    """Supprime les données et structures liées à Etape"""
    db_alias = schema_editor.connection.alias
    
    with connection.cursor() as cursor:
        # Supprimer l'index sur etape si il existe
        try:
            cursor.execute("SHOW INDEX FROM taches WHERE Key_name = 'taches_etape_i_a2cd10_idx'")
            if cursor.fetchone():
                cursor.execute("ALTER TABLE taches DROP INDEX taches_etape_i_a2cd10_idx")
        except Exception:
            pass  # L'index n'existe pas
        
        # Supprimer la colonne etape_id si elle existe
        try:
            cursor.execute("SHOW COLUMNS FROM taches LIKE 'etape_id'")
            if cursor.fetchone():
                cursor.execute("ALTER TABLE taches DROP COLUMN etape_id")
        except Exception:
            pass  # La colonne n'existe pas
        
        # Supprimer la table etapes si elle existe
        try:
            cursor.execute("DROP TABLE IF EXISTS etapes")
        except Exception:
            pass  # La table n'existe pas


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_etape_model'),
        ('notifications', '0002_remove_etape_model'),
        ('projects', '0011_tache_etape_alter_tache_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Supprimer les structures liées à Etape
        migrations.RunPython(
            code=remove_etape_related_data,
            reverse_code=migrations.RunPython.noop,
        ),
        # Ajouter le champ phase_etat à Tache
        migrations.AddField(
            model_name='tache',
            name='phase_etat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projects.projetphaseetat', verbose_name='Phase du projet'),
        ),
        # Ajouter l'index sur phase_etat
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['phase_etat'], name='taches_phase_e_a1349b_idx'),
        ),
    ]
