# Generated by Django 5.2.5 on 2025-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_etape_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('termine', 'Terminé'), ('en_attente', 'En attente'), ('en_cours', 'En cours'), ('hors_delai', 'Hors délai'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
