# Generated by Django 5.2.5 on 2025-10-26 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du widget')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('widget_type', models.CharField(max_length=50, verbose_name='Type de widget')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('position_x', models.IntegerField(default=0, verbose_name='Position X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Position Y')),
                ('width', models.IntegerField(default=4, verbose_name='Largeur')),
                ('height', models.IntegerField(default=3, verbose_name='Hauteur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Widget de tableau de bord',
                'verbose_name_plural': 'Widgets de tableau de bord',
                'db_table': 'analytics_dashboard_widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la métrique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('projects', 'Projets'), ('users', 'Utilisateurs'), ('documents', 'Documents'), ('tasks', 'Tâches'), ('performance', 'Performance'), ('system', 'Système')], max_length=50, verbose_name='Catégorie')),
                ('metric_type', models.CharField(choices=[('count', 'Compteur'), ('percentage', 'Pourcentage'), ('duration', 'Durée'), ('currency', 'Monétaire'), ('ratio', 'Ratio')], max_length=20, verbose_name='Type de métrique')),
                ('value', models.FloatField(verbose_name='Valeur')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('period_start', models.DateTimeField(verbose_name='Début de période')),
                ('period_end', models.DateTimeField(verbose_name='Fin de période')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculé le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Métrique',
                'verbose_name_plural': 'Métriques',
                'db_table': 'analytics_metrics',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['category', 'calculated_at'], name='analytics_m_categor_98249d_idx'), models.Index(fields=['period_start', 'period_end'], name='analytics_m_period__4821ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('report_type', models.CharField(max_length=50, verbose_name='Type de rapport')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('data', models.JSONField(default=dict, verbose_name='Données')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('period_start', models.DateTimeField(verbose_name='Début de période')),
                ('period_end', models.DateTimeField(verbose_name='Fin de période')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'analytics_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='Utilisation CPU (%)')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='Utilisation mémoire (%)')),
                ('disk_usage', models.FloatField(default=0.0, verbose_name='Utilisation disque (%)')),
                ('active_users', models.IntegerField(default=0, verbose_name='Utilisateurs actifs')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Requêtes totales')),
                ('error_rate', models.FloatField(default=0.0, verbose_name="Taux d'erreur (%)")),
                ('db_connections', models.IntegerField(default=0, verbose_name='Connexions DB')),
                ('db_query_time', models.FloatField(default=0.0, verbose_name='Temps de requête moyen (ms)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Santé du système',
                'verbose_name_plural': 'Santé du système',
                'db_table': 'analytics_system_health',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_s_timesta_7e02f0_idx')],
            },
        ),
    ]
