# Generated by Django 5.2.5 on 2025-09-15 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_etape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(blank=True, choices=[('fiche_projet_marketing', 'Fiche projet marketing'), ('fiche_plan_projet', 'Fiche plan projet'), ('fiche_etude_si', "Fiche d'étude SI"), ('fiche_etude_technique', "Fiche d'étude technique"), ('fiche_etude_financiere', "Fiche d'étude financière"), ('fiche_specifications_marketing', 'Fiche de spécifications marketing'), ('fiche_implementation', "Fiche d'implémentation"), ('fiche_recette_uat', 'Fiche de recette utilisateur (UAT)'), ('fiche_lancement_commercial', 'Fiche de lancement commercial'), ('fiche_suppression', 'Fiche de suppression'), ('fiche_bilan_3_mois', 'Fiche de bilan à 3 mois'), ('fiche_bilan_6_mois', 'Fiche de bilan à 6 mois'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Type de document')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('chemin_fichier', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('final', 'Final'), ('rejete', 'Rejeté')], default='final', max_length=20, verbose_name='Statut')),
                ('origine', models.CharField(choices=[('genere', 'Généré'), ('manuel', 'Manuel')], default='manuel', max_length=20, verbose_name='Origine')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du fichier')),
                ('taille_fichier', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('depose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_deposes', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par')),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.etape', verbose_name='Étape')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.projetphaseetat', verbose_name='Phase')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Document de projet',
                'verbose_name_plural': 'Documents de projet',
                'db_table': 'documents_projet',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireDocumentProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('modifie', models.BooleanField(default=False, verbose_name='Modifié')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='documents.commentairedocumentprojet', verbose_name='Commentaire parent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='documents.documentprojet', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Commentaire de document de projet',
                'verbose_name_plural': 'Commentaires de documents de projet',
                'db_table': 'documents_projet_commentaires',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDocumentProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('changement_statut', 'Changement de statut'), ('upload', 'Upload de fichier'), ('suppression', 'Suppression'), ('validation', 'Validation'), ('rejet', 'Rejet')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nouveau statut')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='documents.documentprojet', verbose_name='Document')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de document de projet',
                'verbose_name_plural': 'Historiques de documents de projet',
                'db_table': 'documents_projet_historique',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='documentprojet',
            index=models.Index(fields=['projet', 'type_document', 'cree_le'], name='documents_p_projet__4c6d60_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprojet',
            index=models.Index(fields=['statut'], name='documents_p_statut_7cc9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprojet',
            index=models.Index(fields=['origine'], name='documents_p_origine_8cd513_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprojet',
            index=models.Index(fields=['phase'], name='documents_p_phase_i_46c587_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprojet',
            index=models.Index(fields=['etape'], name='documents_p_etape_i_33e9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='commentairedocumentprojet',
            index=models.Index(fields=['document', 'date_creation'], name='documents_p_documen_da03ab_idx'),
        ),
        migrations.AddIndex(
            model_name='commentairedocumentprojet',
            index=models.Index(fields=['auteur'], name='documents_p_auteur__c950b8_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedocumentprojet',
            index=models.Index(fields=['document', 'date_action'], name='documents_p_documen_87b773_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedocumentprojet',
            index=models.Index(fields=['utilisateur'], name='documents_p_utilisa_d01e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquedocumentprojet',
            index=models.Index(fields=['action'], name='documents_p_action_fc701b_idx'),
        ),
    ]
