# Generated by Django 5.2.5 on 2025-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentairedocumentprojet',
            name='date_modification_fichier',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière modification du fichier'),
        ),
    ]
