# Generated by Django 5.2.5 on 2025-09-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_file_modification_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprojet',
            name='date_modification_fichier',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière modification du fichier'),
        ),
    ]
