# Generated by Django 5.2.5 on 2025-09-16 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_file_modification_tracking_to_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquedocumentprojet',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('changement_statut', 'Changement de statut'), ('upload', 'Upload de fichier'), ('suppression', 'Suppression'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('synchronisation_forcee', 'Synchronisation forcée')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='historiquedocumentprojet',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
