# Generated by Django 5.2.5 on 2025-09-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_update_historique_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquedocumentprojet',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('changement_statut', 'Changement de statut'), ('upload', 'Upload de fichier'), ('suppression', 'Suppression'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('synchronisation_forcee', 'Synchronisation forcée'), ('modification_synchronisee', 'Modification synchronisée')], max_length=50, verbose_name='Action'),
        ),
    ]
