# Generated by Django 5.2.5 on 2025-10-12 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_add_sync_actions'),
        ('projects', '0007_etape'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTeleverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier_original', models.CharField(max_length=255, verbose_name='Nom du fichier original')),
                ('nom_fichier_stocke', models.CharField(max_length=255, verbose_name='Nom du fichier stocké')),
                ('chemin_fichier', models.CharField(max_length=500, verbose_name='Chemin du fichier')),
                ('taille_fichier', models.BigIntegerField(verbose_name='Taille du fichier (en octets)')),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Document Word'), ('doc', 'Document Word (ancien format)'), ('xlsx', 'Fichier Excel'), ('xls', 'Fichier Excel (ancien format)'), ('pptx', 'Présentation PowerPoint'), ('ppt', 'Présentation PowerPoint (ancien format)'), ('jpg', 'Image JPEG'), ('jpeg', 'Image JPEG'), ('png', 'Image PNG'), ('gif', 'Image GIF'), ('bmp', 'Image BMP'), ('tiff', 'Image TIFF'), ('txt', 'Fichier texte'), ('csv', 'Fichier CSV'), ('zip', 'Archive ZIP'), ('rar', 'Archive RAR'), ('autre', 'Autre')], max_length=10, verbose_name='Type de fichier')),
                ('extension_fichier', models.CharField(max_length=10, verbose_name='Extension du fichier')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du document')),
                ('mots_cles', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mots-clés')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version du document')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('archive', 'Archivé')], default='en_attente', max_length=20, verbose_name='Statut du document')),
                ('date_televersement', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
                ('commentaire_validation', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
                ('est_public', models.BooleanField(default=False, verbose_name='Document public')),
                ('hash_fichier', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash du fichier (SHA-256)')),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_televerses', to='projects.etape', verbose_name='Étape associée')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_televerses', to='projects.projetphaseetat', verbose_name='Phase associée')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_televerses', to='projects.projet', verbose_name='Projet associé')),
                ('televerse_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_televerses', to=settings.AUTH_USER_MODEL, verbose_name='Téléversé par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Document téléversé',
                'verbose_name_plural': 'Documents téléversés',
                'db_table': 'documents_televerses',
                'ordering': ['-date_televersement'],
                'indexes': [models.Index(fields=['projet', 'date_televersement'], name='documents_t_projet__0e4740_idx'), models.Index(fields=['phase', 'date_televersement'], name='documents_t_phase_i_54f875_idx'), models.Index(fields=['etape', 'date_televersement'], name='documents_t_etape_i_f6f05d_idx'), models.Index(fields=['televerse_par', 'date_televersement'], name='documents_t_telever_51ed13_idx'), models.Index(fields=['statut', 'date_televersement'], name='documents_t_statut_8a79fb_idx'), models.Index(fields=['type_fichier', 'date_televersement'], name='documents_t_type_fi_c9a36b_idx')],
            },
        ),
    ]
