# Generated by Django 5.2.5 on 2025-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentteleverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentteleverse',
            name='fonction_validateur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction du validateur'),
        ),
        migrations.AddField(
            model_name='documentteleverse',
            name='nom_validateur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du validateur'),
        ),
    ]
