# Generated by Django 5.2.5 on 2025-11-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentteleverse_fonction_validateur_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentprojet',
            name='documents_p_etape_i_33e9a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentteleverse',
            name='documents_t_etape_i_f6f05d_idx',
        ),
        migrations.RemoveField(
            model_name='documentprojet',
            name='etape',
        ),
        migrations.RemoveField(
            model_name='documentteleverse',
            name='etape',
        ),
    ]
